pep:
  image: 912028902405.dkr.ecr.eu-west-1.amazonaws.com/policy_enforcement_proxy:master
  environment:
    OPENAM_POLICY_ENDPOINT_URL: ${OPENAM_POLICY_ENDPOINT_URL}
    OPENAM_POLICY_ENDPOINT_METHOD: ${OPENAM_POLICY_ENDPOINT_METHOD}
    OPENAM_POLICY_APPLICATION_NAME: ${OPENAM_POLICY_APPLICATION_NAME}
    HEADER_PREFIX: ${HEADER_PREFIX}
    PORT: ${PORT}
    UPSTREAM_NAME: ${UPSTREAM_NAME}
    UPSTREAM_PORT: ${UPSTREAM_PORT}
  stdin_open: true
  tty: true
  external_links:
  - pep-manual/test:api
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.global: 'true'
api:
  image: ${IMAGE}:${BRANCH}
  environment:
    AGGREGATOR_HOST: aggregator
    AGGREGATOR_PORT: 80
    ENVIRONMENT: ${ENVIRONMENT}
    MYSQL_CORE_DATABASE: ${MYSQL_CORE_DATABASE}}
    MYSQL_CORE_HOST: ${MYSQL_CORE_HOST}
    MYSQL_CORE_PASSWORD: ${MYSQL_CORE_PASSWORD}
    MYSQL_CORE_USER: ${MYSQL_CORE_USER}
    MYSQL_CONTACTS_DATABASE: ${MYSQL_CONTACTS_DATABASE}
    MYSQL_CONTACTS_HOST: ${MYSQL_CONTACTS_HOST}
    MYSQL_CONTACTS_USER: ${MYSQL_CONTACTS_USER}
    MYSQL_CONTACTS_PASSWORD: ${MYSQL_CONTACTS_PASSWORD}
    MYSQL_ASSETS_DATABASE: ${MYSQL_ASSETS_DATABASE}
    MYSQL_ASSETS_HOST: ${MYSQL_ASSETS_HOST}
    MYSQL_ASSETS_USER: ${MYSQL_ASSETS_USER}
    MYSQL_ASSETS_PASSWORD: ${MYSQL_ASSETS_PASSWORD}
    REAPER_PRO_TYPE: ${REAPER_PRO_TYPE}
    MONGO_USER: ${MONGO_USER}
    MONGO_PASSWORD: ${MONGO_PASSWORD}
    ACCEPTED_TYPE1: ${ACCEPTED_TYPE1}
    ACCEPTED_TYPE2: ${ACCEPTED_TYPE2}
    MYSQL_MOBILE_SETTINGS_DATABASE: ${MYSQL_MOBILE_SETTINGS_DATABASE}
    MYSQL_MOBILE_SETTINGS_HOST: ${MYSQL_MOBILE_SETTINGS_HOST}
    MYSQL_MOBILE_SETTINGS_USER: ${MYSQL_MOBILE_SETTINGS_USER}
    MYSQL_MOBILE_SETTINGS_PASSWORD: ${MYSQL_MOBILE_SETTINGS_PASSWORD}
  stdin_open: true
  external_links:
  - ControlCenter-Infra/db-maria:mysql
  - ControlCenter-Infra/db-mongo:mongo
  - ControlCenter-v2-TEM/service-aggregate:aggregate
  - ControlCenter-Infra/host-lb-dmz-prod-api-mobile:api-mobile.controlcenter.lu
  - ControlCenter-Infra/host-lb-dmz-prod-apps:apps.controlcenter.lu
  - ControlCenter-Infra/host-lb-dmz-prod-cc:cc.post.lu
  tty: true
  labels:
    io.rancher.container.pull_image: always  