version: '2'
services:
  pep:
    image: docker.io/sseidenthal/pep
    environment:
      OPENAM_POLICY_ENDPOINT_URL: ${OPENAM_POLICY_ENDPOINT_URL}
      OPENAM_POLICY_ENDPOINT_METHOD: POST
      OPENAM_POLICY_APPLICATION_NAME: ${OPENAM_POLICY_APPLICATION_NAME}
      HEADER_PREFIX: ${HEADER_PREFIX}
      RESOLVER: ${RESOLVER}
    stdin_open: true
    dns:
    - ${RESOLVER}
    tty: true
    links:
    - api:api
    labels:
      traefik.frontend.rule: Host:${DOMAIN_NAME};PathPrefixStrip:${API_PATH_PREFIX}
      traefik.port: '80'
      traefik.enable: 'true'
      io.rancher.scheduler.global: 'true'

  api:
    image: ${IMAGE}:${IMAGE_TAG}
    secrets:
      - ${DATABASE_USERNAME_FILE}
      - ${DATABASE_PASSWORD_FILE}
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: mysql
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME_FILE: /run/secrets/${DATABASE_USERNAME_FILE}
      DATABASE_PASSWORD_FILE: /run/secrets/${DATABASE_PASSWORD_FILE}
      LOGGED_USER: ${LOGGED_USER}
      UPLOAD_FOLDER: ${UPLOAD_FOLDER}
    stdin_open: true
    external_links:
    - ${DATABASE_HOST}:mysql
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
