version: '2'
services:
  pep:
    image: docker.io/sseidenthal/pep
    environment:
      OPENAM_POLICY_ENDPOINT_URL: ${OPENAM_POLICY_ENDPOINT_URL}
      OPENAM_POLICY_ENDPOINT_METHOD: POST
      OPENAM_POLICY_APPLICATION_NAME: ${OPENAM_POLICY_APPLICATION_NAME}
      HEADER_PREFIX: ${HEADER_PREFIX}
      RESOLVER: ${RESOLVER}
    stdin_open: true
    dns:
    - ${RESOLVER}
    tty: true
    links:
    - api:api
    labels:
      traefik.frontend.rule: Host:${DOMAIN_NAME};PathPrefixStrip:${API_PATH_PREFIX}
      traefik.port: '80'
      traefik.enable: 'true'
      io.rancher.scheduler.global: 'true'
  api:
    image: emilevauge/whoami
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
      
#  api:
#    image: 912028902405.dkr.ecr.eu-west-1.amazonaws.com/pcc_file_repository:qa
#    environment:
#      DATABASE_NAME: api_file_repository
#      DATABASE_HOST: mysql
#      DATABASE_PORT: '3306'
#      DATABASE_USERNAME: root
#      DATABASE_PASSWORD: b1gmac4fr33
#      LOGGED_USER: homer_simpson
#      UPLOAD_FOLDER: /var/www/html/uploads/
#    stdin_open: true
#    external_links:
#    - infrastructure/mysql-server:mysql
#    tty: true
#    labels:
#      io.rancher.container.pull_image: always
#      io.rancher.scheduler.global: 'true'
